## 1. Numpy

In [2]:
import numpy as np

In [8]:
# 1차원
arr1 = np.array([1, 2, 3])
arr1

arr1.ndim, arr1.dtype, arr1.shape

(1, dtype('int32'), (3,))

In [7]:
arr2 = np.array([[1, 2, 3], [4, 5,6]])

arr2
arr2.ndim, arr2.dtype, arr2.shape

(2, dtype('int32'), (2, 3))

In [6]:
test = [1, 2.5, 3.5]
arr = np.array(test)

arr.shape, arr.dtype

((3,), dtype('float64'))

In [10]:
test = ['1', '2', '3', '4', '5']
arr = np.array(test)

arr = arr.astype(np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [14]:
arr = np.arange(10)
print(arr, arr[:4])

arr[arr>5] # true 라는 인덱스를 받아서 boolean값으로 가져온것


[0 1 2 3 4 5 6 7 8 9] [0 1 2 3]


array([6, 7, 8, 9])

In [17]:
np.ones([10,10], dtype='int64')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [19]:
# reshape 차원 변경
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])